[package]
name = "tipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tlib = { path = "../tlib/" }

log = "0.4"

[dev-dependencies]
ctrlc = "3.2.5"

[[example]]
name = "ipc_test"
dependencies = [
    "ctrlc"
]