[package]
name = "tlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { path = "../macros/" }

log = "0.4"
lazy_static = "1.4.0"
once_cell = "1.17.0"
strum = "0.24.1"
strum_macros = "0.24"
tokio = { version = "1.28.0", features = ["full"] }
