[package]
name = "tmui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tipc = { path = "../tipc/" }
tlib = { path = "../tlib/" }

log = "0.4"
skia-safe = { version = "0.57.0", features = ["gl"] }
glutin = "0.30.3"
hex_color = "2.0.0"
lazy_static = "1.4.0"
once_cell = "1.17.0"
widestring = "1.0.2"

windows = { version = "0.43.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
] }

[dev-dependencies]
log4rs = "1.1.1"

[[example]]
name = "win32_window"
